In [16]:
import numpy as np
import pandas as pd

#### 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [17]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = X.shape[0]
b = (np.mean(X*y) - np.mean(X)*np.mean(y))/(np.mean(X**2)-np.mean(X)**2)

print('b = {}'.format(b))

b = 2.620538882402765


In [18]:
b = (n*((X*y).sum()) - (X.sum()*y.sum()))/(n*((X**2).sum())-((X.sum()**2)))
b

2.6205388824027653

In [19]:
a = np.mean(y)-b*np.mean(X)
a

444.17735732435955

In [20]:
y_hat = a + b*X
y_hat

array([535.89621821, 562.10160703, 942.07974498, 968.2851338 ,
       548.99891262, 627.61507909, 585.68645697, 837.25818968,
       758.64202321, 732.43663439])

In [21]:
mse=((y-y_hat)**2).sum()/n
mse

6470.414201176658

###### 2 способ (при множестве независимых переменных)

In [22]:
import seaborn as sns

In [23]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = X.shape[0]

In [24]:
y = y.reshape((10,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [25]:
X = X.reshape((10,1))
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [26]:
X=np.hstack([np.ones((10, 1)), X])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [27]:
B = np.dot(np.linalg.inv(np.dot(X.T,X)),X.T @y)
B

array([[444.17735732],
       [  2.62053888]])

#### 2. Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск.

In [28]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = X.shape[0]

In [29]:
## mse_p=(2/n)*np.sum((B1*X-y)*X)
## mse=(1/n)*np.sum((B1*X-y)**2)

In [30]:
alpha=1e-6

In [31]:
def mse_(B1, y=y,X=X,n=10):
    return np.sum((B1*X-y)**2)/n

In [32]:
mse_(1.77549)

289723.2142124616

In [33]:
B1=0.1
n=10

In [34]:
for i in range (10):
    B1 -=alpha*(2/n)*np.sum((B1*X-y)*X)
    print('B1={}'.format(B1))

B1=0.25952808
B1=0.414660650906144
B1=0.5655188230595969
B1=0.7122203698240712
B1=0.8548798195302346
B1=0.9936085448867542
B1=1.1285148499277806
B1=1.2597040545647504
B1=1.387278576808517
B1=1.5113380127259965


In [35]:
for i in range (100):
    B1 -=alpha*(2/n)*np.sum((B1*X-y)*X)
    if i%10==0:
        print('Iteration: {i},B1={B1}, mse={mse}'.format(i=i, B1=B1, mse=mse_(B1)))

Iteration: 0,B1=1.6319792141937546, mse=306275.7568040035
Iteration: 10,B1=2.6698789606516935, mse=199352.96411174876
Iteration: 20,B1=3.4547782236263824, mse=138204.25062502263
Iteration: 30,B1=4.04834889855975, mse=103233.54824312925
Iteration: 40,B1=4.497229618367758, mse=83233.94472982832
Iteration: 50,B1=4.836690291080364, mse=71796.25222021657
Iteration: 60,B1=5.093403362579137, mse=65255.0820486468
Iteration: 70,B1=5.287539550879594, mse=61514.21323463749
Iteration: 80,B1=5.434352720103083, mse=59374.825462025976
Iteration: 90,B1=5.54537842245223, mse=58151.31823171113


#### 3. В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента?

In [36]:
# Таблица значений функции Лапласа применяется, когда число испытаний n достаточно велико 
# Таблица критических точек распределения Стьюдента используется при малых выборках и в случае, если мы не знаем дисперсию генеральной совокупности

#### 4. Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).

In [37]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = X.shape[0]
alpha=1e-6

In [38]:
B0=10
B1=0.1

In [39]:
def mse_(B0, B1, y=y, X=X, n=n):
    return np.sum((B0 + B1*X - y)**2)/n

In [41]:
for i in range (100000):
    B0 -=alpha*(2/n)*np.sum(B0 + B1*X - y)
    B1 -=alpha*(2/n)*np.sum((B0 + B1*X - y)*X)
    if i%10000==0:
        print('Iteration: {i}, B0={B0}, B1={B1}, mse={mse}'.format(i=i, B0=B0, B1=B1, mse=mse_(B0, B1)))

Iteration: 0, B0=31.516763281029714, B1=5.657903259835761, mse=49666.69872524247
Iteration: 10000, B0=33.60490268552237, B1=5.642532140069896, mse=49230.64230717359
Iteration: 20000, B0=35.68247572692948, B1=5.627240291694519, mse=48798.98777691631
Iteration: 30000, B0=37.74953586204272, B1=5.612025822918235, mse=48371.690698472245
Iteration: 40000, B0=39.806136288124826, B1=5.59688834218587, mse=47948.70708438156
Iteration: 50000, B0=41.8523299332507, B1=5.581827459923589, mse=47529.99339122748
Iteration: 60000, B0=43.8881694576688, B1=5.5668427885288745, mse=47115.50651515405
Iteration: 70000, B0=45.913707255157185, B1=5.551933942360556, mse=46705.2037874286
Iteration: 80000, B0=47.92899545437189, B1=5.537100537728869, mse=46299.04297004935
Iteration: 90000, B0=49.93408592018708, B1=5.522342192885601, mse=45896.98225139746
