In [98]:
import numpy as np
import pandas as pd

#### 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [99]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = X.shape[0]
b = (np.mean(X*y) - np.mean(X)*np.mean(y))/(np.mean(X**2)-np.mean(X)**2)

print('b = {}'.format(b))

b = 2.620538882402765


In [100]:
b = (n*((X*y).sum()) - (X.sum()*y.sum()))/(n*((X**2).sum())-((X.sum()**2)))
b

2.6205388824027653

In [101]:
a = np.mean(y)-b*np.mean(X)
a

444.17735732435955

In [102]:
y_hat = a + b*X
y_hat

array([535.89621821, 562.10160703, 942.07974498, 968.2851338 ,
       548.99891262, 627.61507909, 585.68645697, 837.25818968,
       758.64202321, 732.43663439])

In [103]:
mse=((y-y_hat)**2).sum()/n
mse

6470.414201176658

###### 2 способ (при множестве независимых переменных)

In [104]:
import seaborn as sns

In [105]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = X.shape[0]

In [106]:
y = y.reshape((10,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [107]:
X = X.reshape((10,1))
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [108]:
X=np.hstack([np.ones((10, 1)), X])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [109]:
B = np.dot(np.linalg.inv(np.dot(X.T,X)),X.T @y)
B

array([[444.17735732],
       [  2.62053888]])

#### 2. Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск.

In [110]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = X.shape[0]

In [111]:
## mse_p=(2/n)*np.sum((B1*X-y)*X)
## mse=(1/n)*np.sum((B1*X-y)**2)

In [112]:
alpha=1e-6

In [113]:
def mse_(B1, y=y,X=X,n=10):
    return np.sum((B1*X-y)**2)/n

In [114]:
B1=0.1
n=10

In [115]:
for i in range (10):
    B1 -=alpha*(2/n)*np.sum((B1*X-y)*X)
    print('B1={}'.format(B1))

B1=0.25952808
B1=0.414660650906144
B1=0.5655188230595969
B1=0.7122203698240712
B1=0.8548798195302346
B1=0.9936085448867542
B1=1.1285148499277806
B1=1.2597040545647504
B1=1.387278576808517
B1=1.5113380127259965


In [116]:
for i in range (1000):
    B1 -=alpha*(2/n)*np.sum((B1*X-y)*X)
    if i%100==0:
        print('Iteration: {i}, B1={B1}, mse={mse}'.format(i=i, B1=B1, mse=mse_(B1)))

Iteration: 0, B1=1.6319792141937546, mse=306275.7568040035
Iteration: 100, B1=5.629340281237233, mse=57451.59938606899
Iteration: 200, B1=5.873885137561711, mse=56520.35675226433
Iteration: 300, B1=5.888845554134484, mse=56516.87150850017
Iteration: 400, B1=5.889760781170516, mse=56516.85846472009
Iteration: 500, B1=5.889816771625289, mse=56516.8584159028
Iteration: 600, B1=5.889820196929507, mse=56516.85841572009
Iteration: 700, B1=5.8898204064778845, mse=56516.85841571941
Iteration: 800, B1=5.889820419297334, mse=56516.85841571941
Iteration: 900, B1=5.889820420081584, mse=56516.85841571941


In [117]:
mse_(5.88982)

56516.85841572182

#### 3. В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента?

In [118]:
# Таблица значений функции Лапласа применяется, когда число испытаний n достаточно велико 
# Таблица критических точек распределения Стьюдента используется при малых выборках и в случае, если мы не знаем дисперсию генеральной совокупности

#### 4. Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).

In [119]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = X.shape[0]
alpha=1e-6

In [120]:
B0=10
B1=0.1

In [121]:
def mse_(B0, B1, y=y, X=X, n=n):
    return np.sum((B0 + B1*X - y)**2)/n

In [122]:
for i in range (100000):
    B0 -=alpha*(2/n)*np.sum(B0 + B1*X - y)
    B1 -=alpha*(2/n)*np.sum((B0 + B1*X - y)*X)
    if i%10000==0:
        print('Iteration: {i}, B0={B0}, B1={B1}, mse={mse}'.format(i=i, B0=B0, B1=B1, mse=mse_(B0, B1)))

Iteration: 0, B0=10.00137952, B1=0.25749980023334396, mse=479974.7807697668
Iteration: 10000, B0=12.23909656541245, B1=5.799793839704354, mse=53796.844216388265
Iteration: 20000, B0=14.424784562661086, B1=5.783706217857293, mse=53319.09494277988
Iteration: 30000, B0=16.59941257181577, B1=5.767700002371208, mse=52846.16843666866
Iteration: 40000, B0=18.763036558474912, B1=5.751774781314763, mse=52378.01601334142
Iteration: 50000, B0=20.91571220504043, B1=5.735930144841069, mse=51914.58947954595
Iteration: 60000, B0=23.05749491215109, B1=5.720165685177134, mse=51455.84112852954
Iteration: 70000, B0=25.188439800108153, B1=5.70448099661338, mse=51001.72373512808
Iteration: 80000, B0=27.308601710293637, B1=5.6888756754931915, mse=50552.19055090448
Iteration: 90000, B0=29.418035206582534, B1=5.673349320202528, mse=50107.195299336134
